Package updgrade fixes
ello/webapp pull request #525
Opened 2022-03-22 10:23 UTC by ansh-k

2022-07-12 05:49 UTC, usmanchaudhryme requested changes
Great work Anshu! So many amazing update to review. 
Just a few things to note:
1. There are plenty of warnings related to deprecated methods like `componentWillMount`, `componentWillReceiveProps`, etc. Can you make sure they're all taken care of, if you believe it's more work and shouldn't be part of this PR you can create a new branch and work there. 

2. Same goes for PropTypes, warnings are there ensure that either they're relevant or remove them accordingly. 

3. Individual comments below

I've reviewed about 20% of the PR, will do another session again.

2022-07-12 05:49 UTC, usmanchaudhryme commented on src/components/artist_invites/ArtistInviteRenderables.js
> +import Immutable from 'immutable'
This one can be added as `import { Map } from 'immutable'` and follow-up implementation doesn't need to explicitly add Immutable with every call.

2022-07-12 05:49 UTC, usmanchaudhryme commented on src/components/artist_invites/ArtistInviteRenderables.js
> +        <ImageAsset className={logoImageStyle} src={Immutable.Map(logoImage).getIn(['optimized', 'url'])} />
Preferably process `logoImage` and other immutable types within the createSelector where you can wrap the `ai.get` with relevant Map.  file:`artist_invties.js`. So this one can stay as `logoImage.getIn` instead of `Map(logoImage).getIn`.

2022-07-12 05:49 UTC, usmanchaudhryme commented on src/components/artist_invites/ArtistInviteRenderables.js
> +            <div className={guideStyle} key={`guide_${Immutable.Map(g).get('title')}`}>
Same as above.

2022-07-12 08:31 UTC, ansh-k commented on src/components/artist_invites/ArtistInviteRenderables.js
> +import Immutable from 'immutable'
Sure I will take care, Thanks

2022-07-22 12:47 UTC, ansh-k commented
> 

Fixed pushed change 
For point 1 PR: https://github.com/ello/webapp/pull/552
For point 2 PR: https://github.com/ello/webapp/pull/550

2022-08-08 04:27 UTC, usmanchaudhryme commented
@ansh-k Looks much better now. Can you please merge the relevant PRs so that I can review them once more?

2022-08-09 13:16 UTC, usmanchaudhryme approved these changes
Good work, let's merge it, just one question around availability though.

2022-08-09 13:16 UTC, usmanchaudhryme commented on src/components/forms/RegistrationRequestForm.js
> +    // availability: PropTypes.object,
Ideally take it out completely if we're not using it anymore or keep it there. From what I can tell, we're still using it.

2022-08-09 13:19 UTC, ansh-k commented on src/components/forms/RegistrationRequestForm.js
> +    // availability: PropTypes.object,
My bad, i going to remove it

2022-10-31 14:36 UTC, merged