Show signup blocklisting message
ello/webapp pull request #539
Opened 2022-05-24 11:39 UTC by rajeshupwk

when request is blacklisted

2022-05-24 16:06 UTC, aka47 approved these changes
looks good to me .. yes.

2022-05-25 10:15 UTC, aka47 requested changes
Nice. On little naming thing

2022-05-25 10:15 UTC, aka47 commented on src/components/forms/JoinForm.js
> +        { errors && errors.code === 'blacklisted' && <p>{ERROR_MESSAGES.REQUEST.BLACKLISTED}</p> }
Can we call it blocklisted .. that is the standard for it everywhere now..

2022-05-25 14:07 UTC, rajeshupwk commented on src/components/forms/JoinForm.js
> +        { errors && errors.code === 'blacklisted' && <p>{ERROR_MESSAGES.REQUEST.BLACKLISTED}</p> }
We can call it but for doing so, again we need to modify the Ello [file](https://github.com/ello/ello/blob/9c5db623cc22cff45be56cccd2718d8d6abb662e/lib/api/controller/error_handling.rb#L6)

2022-05-25 14:21 UTC, aka47 commented on src/components/forms/JoinForm.js
> +        { errors && errors.code === 'blacklisted' && <p>{ERROR_MESSAGES.REQUEST.BLACKLISTED}</p> }
sure.. lets change it .. all gems use blocklisted now.

2022-06-02 06:52 UTC, aka47 approved these changes
yes, nice

2022-06-03 10:41 UTC, merged